# Generated by Django 5.2.17 on 2026-10-05 16:43

import apps.accounts.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^09\\d{9}$",
                                "شماره موبایل باید ۱۱ رقم و با ۰۹ شروع شود.",
                            )
                        ],
                        verbose_name="موبایل",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="ایمیل",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=80, verbose_name="نام"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="نام خانوادگی"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="avatars/", verbose_name="تصویر"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="شرکت / سازمان"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=100, verbose_name="سمت"),
                ),
                (
                    "mobile_verified",
                    models.BooleanField(default=False, verbose_name="موبایل تأیید شده"),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(db_index=True, max_length=11)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "کد یک\u200cبارمصرف",
                "verbose_name_plural": "کدهای یک\u200cبارمصرف",
                "ordering": ["-created_at"],
            },
        ),
    ]
