# Generated by Django 5.2.17 on 2026-10-05 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=30, unique=True, verbose_name="شناسه"),
                ),
                ("name", models.CharField(max_length=60, verbose_name="نام پلن")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="توضیح کوتاه"
                    ),
                ),
                (
                    "price_monthly",
                    models.PositiveIntegerField(
                        default=0, verbose_name="قیمت ماهانه (تومان)"
                    ),
                ),
                (
                    "price_yearly",
                    models.PositiveIntegerField(
                        default=0, verbose_name="قیمت سالانه (تومان)"
                    ),
                ),
                (
                    "max_surveys",
                    models.PositiveIntegerField(
                        default=3, help_text="۰ = نامحدود", verbose_name="حداکثر فرم"
                    ),
                ),
                (
                    "max_responses_month",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="۰ = نامحدود",
                        verbose_name="حداکثر پاسخ در ماه",
                    ),
                ),
                (
                    "max_members",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="۰ = نامحدود",
                        verbose_name="حداکثر عضو تیم",
                    ),
                ),
                (
                    "max_upload_mb",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="حداکثر حجم هر فایل (مگابایت)"
                    ),
                ),
                (
                    "logic",
                    models.BooleanField(default=True, verbose_name="منطق شرطی و پرش"),
                ),
                (
                    "calcs",
                    models.BooleanField(
                        default=False, verbose_name="متغیر، امتیاز و محاسبه"
                    ),
                ),
                (
                    "file_upload",
                    models.BooleanField(default=False, verbose_name="سؤال آپلود فایل"),
                ),
                (
                    "export",
                    models.BooleanField(default=False, verbose_name="خروجی اکسل"),
                ),
                (
                    "remove_branding",
                    models.BooleanField(
                        default=False, verbose_name="حذف «ساخته\u200cشده با»"
                    ),
                ),
                (
                    "custom_theme",
                    models.BooleanField(default=False, verbose_name="طراحی اختصاصی"),
                ),
                (
                    "webhook",
                    models.BooleanField(default=False, verbose_name="وب\u200cهوک"),
                ),
                (
                    "sms_notify",
                    models.BooleanField(default=False, verbose_name="اعلان پیامکی"),
                ),
                (
                    "password",
                    models.BooleanField(default=False, verbose_name="فرم رمزدار"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="پلن پیش\u200cفرض (رایگان)"
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False, verbose_name="پیشنهاد ویژه در صفحه\u200cی قیمت"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
            ],
            options={
                "verbose_name": "پلن",
                "verbose_name_plural": "پلن\u200cها",
                "ordering": ["order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="مدت (ماه)"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("paid", "پرداخت شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Authority",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="کد پیگیری"
                    ),
                ),
                (
                    "card_pan",
                    models.CharField(blank=True, max_length=24, verbose_name="کارت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پرداخت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پرداخت\u200cکننده",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="teams.workspace",
                        verbose_name="فضای کاری",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.plan",
                        verbose_name="پلن",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="شروع"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی = بدون انقضا",
                        null=True,
                        verbose_name="انقضا",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="یادداشت"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.plan",
                        verbose_name="پلن",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="teams.workspace",
                        verbose_name="فضای کاری",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراک",
                "verbose_name_plural": "اشتراک\u200cها",
            },
        ),
    ]
