# Generated by Django 5.2.17 on 2026-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250, verbose_name="سؤال")),
                ("answer", models.TextField(verbose_name="پاسخ")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "پرسش متداول",
                "verbose_name_plural": "پرسش\u200cهای متداول",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("body", models.TextField(verbose_name="متن (HTML ساده)")),
                (
                    "show_in_footer",
                    models.BooleanField(default=True, verbose_name="در فوتر"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "صفحه",
                "verbose_name_plural": "صفحات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="فرم\u200cساز ICSD",
                        max_length=80,
                        verbose_name="نام سامانه",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="ICSD فرم", max_length=30, verbose_name="نام کوتاه"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="فرم و پرسشنامه\u200cی آنلاین حرفه\u200cای، فارسی و بدون کدنویسی",
                        max_length=200,
                        verbose_name="شعار",
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        default="https://s.icsd.ir", verbose_name="آدرس سامانه"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="brand/", verbose_name="لوگو"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, upload_to="brand/", verbose_name="فاوآیکن"
                    ),
                ),
                (
                    "color_primary",
                    models.CharField(
                        default="#1E9E7B", max_length=7, verbose_name="رنگ اصلی"
                    ),
                ),
                (
                    "color_accent",
                    models.CharField(
                        default="#16A9C7", max_length=7, verbose_name="رنگ تأکید"
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="تلفن پشتیبانی",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="ایمیل پشتیبانی",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="کاشان، پارک علم و فناوری دانشگاه کاشان، طبقه\u200cی همکف، واحد ۱۴۴",
                        max_length=250,
                        verbose_name="آدرس",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        default="ساخته\u200cشده در توسعه هوشمند فرش ایرانیان — کاشان",
                        verbose_name="متن فوتر",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        default="ساخت فرم، پرسشنامه، آزمون و نظرسنجی آنلاین فارسی با منطق شرطی، امتیازدهی، گزارش و نمودار.",
                        max_length=300,
                        verbose_name="توضیح متای صفحه\u200cی اصلی",
                    ),
                ),
                (
                    "head_extra_html",
                    models.TextField(
                        blank=True,
                        help_text="مثل کد تأیید سرچ\u200cکنسول. فقط مدیر ارشد.",
                        verbose_name="کد اضافی head",
                    ),
                ),
                (
                    "branding_text",
                    models.CharField(
                        default="ساخته\u200cشده با فرم\u200cساز ICSD",
                        max_length=80,
                        verbose_name="متن «ساخته\u200cشده با» زیر فرم\u200cها",
                    ),
                ),
                (
                    "free_signup",
                    models.BooleanField(
                        default=True, verbose_name="ثبت\u200cنام عمومی باز است"
                    ),
                ),
                (
                    "kavenegar_api_key",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="کلید API کاوه\u200cنگار",
                    ),
                ),
                (
                    "kavenegar_otp_template",
                    models.CharField(
                        default="otp", max_length=50, verbose_name="الگوی پیامک کد ورود"
                    ),
                ),
                (
                    "kavenegar_notify_template",
                    models.CharField(
                        default="newresponse",
                        help_text="الگو با متغیر token (نام فرم) و token2 (تعداد پاسخ\u200cها).",
                        max_length=50,
                        verbose_name="الگوی پیامک «پاسخ جدید»",
                    ),
                ),
                (
                    "zarinpal_merchant_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="مرچنت زرین\u200cپال"
                    ),
                ),
                (
                    "zarinpal_sandbox",
                    models.BooleanField(
                        default=True, verbose_name="زرین\u200cپال آزمایشی"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سامانه",
                "verbose_name_plural": "تنظیمات سامانه",
            },
        ),
    ]
