# Generated by Django 5.2.17 on 2026-10-05 16:43

import apps.surveys.engine
import apps.surveys.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=80,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("business", "کسب\u200cوکار"),
                            ("customer", "مشتری و فروش"),
                            ("hr", "منابع انسانی"),
                            ("education", "آموزش"),
                            ("event", "رویداد و ثبت\u200cنام"),
                            ("research", "پژوهش"),
                            ("general", "عمومی"),
                        ],
                        default="general",
                        max_length=12,
                        verbose_name="دسته",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(default="📋", max_length=8, verbose_name="نماد"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="توضیح"),
                ),
                (
                    "schema",
                    models.JSONField(
                        default=apps.surveys.engine.default_schema,
                        verbose_name="ساختار",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="دفعات استفاده"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
            ],
            options={
                "verbose_name": "قالب آماده",
                "verbose_name_plural": "قالب\u200cهای آماده",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="نام پوشه")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="teams.workspace",
                        verbose_name="فضای کاری",
                    ),
                ),
            ],
            options={
                "verbose_name": "پوشه",
                "verbose_name_plural": "پوشه\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="توکن",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نسخه\u200cی فرم"
                    ),
                ),
                (
                    "answers",
                    models.JSONField(default=dict, verbose_name="پاسخ\u200cها"),
                ),
                ("variables", models.JSONField(default=dict, verbose_name="متغیرها")),
                ("hidden", models.JSONField(default=dict, verbose_name="فیلدهای مخفی")),
                (
                    "path",
                    models.JSONField(default=list, verbose_name="مسیر طی\u200cشده"),
                ),
                (
                    "ending",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="صفحه\u200cی پایان"
                    ),
                ),
                (
                    "last_question",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="آخرین سؤال"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="شروع"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="تکمیل"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, verbose_name="مدت (ثانیه)"),
                ),
                (
                    "device",
                    models.CharField(blank=True, max_length=10, verbose_name="دستگاه"),
                ),
                (
                    "ip_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="هش IP"),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=11,
                        verbose_name="موبایل تأییدشده",
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(
                        default=False, verbose_name="آزمایشی (پیش\u200cنمایش)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ",
                "verbose_name_plural": "پاسخ\u200cها",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "code",
                    models.CharField(
                        default=apps.surveys.models.new_code,
                        max_length=12,
                        unique=True,
                        verbose_name="کد لینک",
                    ),
                ),
                (
                    "draft",
                    models.JSONField(
                        default=apps.surveys.engine.default_schema,
                        verbose_name="ساختار (پیش\u200cنویس)",
                    ),
                ),
                (
                    "published",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ساختار منتشرشده"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=0, verbose_name="نسخه"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشر شده"),
                            ("closed", "بسته"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "has_unpublished",
                    models.BooleanField(default=False, verbose_name="تغییر منتشرنشده"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع پاسخ\u200cگیری"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان پاسخ\u200cگیری"
                    ),
                ),
                (
                    "max_responses",
                    models.PositiveIntegerField(
                        default=0, help_text="۰ = نامحدود", verbose_name="حداکثر پاسخ"
                    ),
                ),
                (
                    "closed_message",
                    models.CharField(
                        blank=True,
                        default="این فرم دیگر پاسخ نمی\u200cپذیرد.",
                        max_length=250,
                        verbose_name="پیام فرم بسته",
                    ),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=50, verbose_name="رمز فرم"),
                ),
                (
                    "one_per_device",
                    models.BooleanField(
                        default=False, verbose_name="هر دستگاه فقط یک بار"
                    ),
                ),
                (
                    "verify_mobile",
                    models.BooleanField(
                        default=False,
                        verbose_name="تأیید موبایل پاسخ\u200cدهنده با کد پیامکی",
                    ),
                ),
                (
                    "one_per_mobile",
                    models.BooleanField(
                        default=False, verbose_name="هر موبایل فقط یک بار"
                    ),
                ),
                (
                    "save_partial",
                    models.BooleanField(
                        default=True,
                        verbose_name="ذخیره\u200cی پاسخ\u200cهای نیمه\u200cکاره",
                    ),
                ),
                (
                    "hidden_fields",
                    models.CharField(
                        blank=True,
                        help_text="نام\u200cها با کاما؛ مثل utm_source,ref — از ?ref=... خوانده می\u200cشوند.",
                        max_length=300,
                        verbose_name="فیلدهای مخفی (از آدرس)",
                    ),
                ),
                (
                    "notify_sms",
                    models.BooleanField(
                        default=False, verbose_name="پیامک برای هر پاسخ جدید"
                    ),
                ),
                (
                    "notify_mobile",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="موبایل دریافت اعلان"
                    ),
                ),
                (
                    "notify_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="ایمیل دریافت اعلان"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="وب\u200cهوک"
                    ),
                ),
                (
                    "response_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد پاسخ"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="حذف\u200cشده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین انتشار"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سازنده",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys",
                        to="surveys.folder",
                        verbose_name="پوشه",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="teams.workspace",
                        verbose_name="فضای کاری",
                    ),
                ),
            ],
            options={
                "verbose_name": "فرم",
                "verbose_name_plural": "فرم\u200cها",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=40)),
                ("file", models.FileField(upload_to="responses/%Y/%m/")),
                ("name", models.CharField(max_length=200)),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="surveys.response",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل پاسخ",
                "verbose_name_plural": "فایل\u200cهای پاسخ",
            },
        ),
        migrations.AddField(
            model_name="response",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="surveys.survey",
                verbose_name="فرم",
            ),
        ),
    ]
