# Generated by Django 5.2.17 on 2026-10-05 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="نام فضای کاری"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک",
                    ),
                ),
            ],
            options={
                "verbose_name": "فضای کاری",
                "verbose_name_plural": "فضاهای کاری",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="موبایل دعوت\u200cشده"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "مالک"),
                            ("admin", "مدیر"),
                            ("editor", "ویرایشگر"),
                            ("viewer", "فقط مشاهده\u200cی نتایج"),
                        ],
                        default="editor",
                        max_length=10,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="teams.workspace",
                        verbose_name="فضای کاری",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضویت",
                "verbose_name_plural": "اعضا",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "user"), name="uniq_ws_user"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True)),
                        fields=("workspace", "mobile"),
                        name="uniq_ws_invite",
                    ),
                ],
            },
        ),
    ]
